recaptcha.validation.secret-key: 6LeK070UAAAAAFPfEKouRAZIG_X265axRusX8Oki
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  http:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB